# Site settings
title: Hatim Ali Kanchwala
description: Personal Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://the-hatim.github.io/"  # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hatim Ali Kanchwala
user_description: Hey there! I'm a Recent Computer Engineering Graduate, always searching for the next challenge; Self-Driven, Result-oriented and a quick learner with a focused mindset and varied technical skills. Critical thinker with a problem-solving attitude and a knack for continuous learning and professional development. Looking for opportunities in Cyber-Security, Software Development, Software Testing Domains. Demonstrated experience developing high quality test scripts, plans and test executions. Well Versed with Programming, Version Control Systems and Testing. 
user_title: Software Developer / Cybersecurity Enthusiast
email: hatimali.ha@gmail.com
# twitter_username: lorem_ipsum
github_username: the-hatim
LinkedIn: hatim-ali-kanchwala

exclude: ['package.json', 'src' , 'node_modules']
